name: Build and Test
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 23 (Adoptium)
      uses: actions/setup-java@v2
      with:
        java-version: '23'
        distribution: 'temurin' 
        
    - name: Run Maven tests
      run: mvn clean test
